import BackButton from '../components/BackButton'

const S: Record<string, React.CSSProperties> = {
  page: { minHeight: '100vh', background: 'var(--bg-primary)', color: 'var(--text-primary)', padding: '0 0 100px' },
  header: { padding: '16px', display: 'flex', alignItems: 'center', gap: 12 },
  title: { fontSize: 20, fontWeight: 700, margin: 0 },
  content: { padding: '0 16px', display: 'flex', flexDirection: 'column', gap: 20 },
  section: { background: 'var(--bg-secondary)', borderRadius: 'var(--radius-lg, 12px)', padding: 16 },
  sectionTitle: { fontSize: 16, fontWeight: 700, margin: '0 0 8px', color: 'var(--text-primary)' },
  sub: { fontSize: 14, fontWeight: 600, margin: '12px 0 4px', color: 'var(--text-primary)' },
  p: { fontSize: 13, lineHeight: 1.6, margin: '0 0 8px', color: 'var(--text-secondary)' },
  list: { fontSize: 13, lineHeight: 1.7, margin: '0 0 8px', paddingLeft: 20, color: 'var(--text-secondary)' },
  badge: { display: 'inline-block', fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 6, background: 'var(--accent, #6366f1)', color: '#fff', marginRight: 6 },
}

export default function HowItWorks() {
  return (
    <div style={S.page}>
      <div style={S.header}>
        <BackButton />
        <h1 style={S.title}>How the Model Works</h1>
      </div>

      <div style={S.content}>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Overview</h2>
          <p style={S.p}>
            Your workout plan is generated by a <strong>deterministic rules engine</strong> — not a black-box neural network.
            Every decision has a traceable reason. The engine combines your training history, biometric data, and
            exercise science research to produce a personalized workout each session.
          </p>
          <p style={S.p}>
            An optional <strong>LLM layer</strong> (GPT-4o-mini) can analyze the generated workout and your data to provide
            narrative insights, but it never makes workout decisions — the engine does.
          </p>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 1: Data Collection</h2>
          <p style={S.sub}>What feeds the model</p>
          <ul style={S.list}>
            <li><strong>Workout logs</strong> — exercises, sets, reps, weight, tempo, rest times, RPE</li>
            <li><strong>Fitbit</strong> — sleep duration, HRV, resting heart rate, steps, calories, active minutes, HR zones</li>
            <li><strong>Body weight</strong> — manually entered only (Fitbit weight is never used)</li>
            <li><strong>Profile</strong> — age, experience level, goals, injuries, equipment, schedule</li>
          </ul>
          <p style={S.p}>
            Data is fetched from the last 120 days. Warmup sets are automatically filtered out using a 65%-of-peak-weight
            heuristic (or explicit warmup flags) so they don't contaminate progression tracking or volume calculations.
          </p>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 2: Feature Engineering</h2>
          <p style={S.p}>Raw data is transformed into ~30 features the engine uses:</p>
          <ul style={S.list}>
            <li><strong>Exercise progressions</strong> — estimated 1RM trend per exercise (Epley formula), plateau detection</li>
            <li><strong>Volume landmarks</strong> — weekly sets per muscle group vs MEV/MAV/MRV thresholds from research</li>
            <li><strong>Recovery context</strong> — last night's sleep, HRV, RHR compared to your 30-day baseline</li>
            <li><strong>Fitness-fatigue model</strong> — Banister impulse-response: fitness decays slowly (τ=42d), fatigue decays fast (τ=7d)</li>
            <li><strong>Body weight trend</strong> — date-aware linear regression on your manual entries to detect cutting/bulking/maintaining</li>
            <li><strong>Performance deltas</strong> — actual vs expected volume load per exercise, correlated with sleep, HRV, time-of-day</li>
            <li><strong>Exercise preferences</strong> — recency-weighted usage patterns (14-day half-life exponential decay)</li>
            <li><strong>Cumulative sleep debt</strong> — 7-day rolling deficit tracking with recovery modifier</li>
          </ul>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 3: Recovery Check</h2>
          <p style={S.p}>Before building the workout, the engine evaluates your recovery state:</p>
          <ul style={S.list}>
            <li>Sleep below 80% of baseline → volume reduced proportionally</li>
            <li>HRV below 85% of baseline → volume reduced ~10%</li>
            <li>RHR elevated 10%+ above baseline → volume reduced ~10%</li>
            <li>Cumulative sleep debt over 7 days → additional recovery modifier</li>
            <li>Multiple exercises regressing + HRV dropping + sleep declining → auto-deload recommended</li>
            <li>Return from 7+ day break → progressive ramp-back (7d=85%, 14d=60%, 21d=50% volume)</li>
          </ul>
          <p style={S.p}>
            Per-muscle-group recovery also tracks synergist fatigue — training chest yesterday adds
            fatigue to triceps and anterior deltoid, even though they weren't directly trained.
          </p>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 4: Exercise Selection</h2>
          <p style={S.p}>The engine selects exercises based on:</p>
          <ul style={S.list}>
            <li><strong>Split rotation</strong> — Push/Pull/Legs, Upper/Lower, Full Body, etc. based on your schedule</li>
            <li><strong>Muscle group needs</strong> — prioritizes groups below MEV or approaching MRV cap</li>
            <li><strong>Your history</strong> — prefers exercises you've done before (recency-weighted)</li>
            <li><strong>Injuries</strong> — excludes exercises that target injured body parts</li>
            <li><strong>Equipment</strong> — only selects exercises matching your gym's equipment</li>
            <li><strong>Plateau breaking</strong> — swaps stalled exercises for alternatives targeting the same muscles</li>
          </ul>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 5: Weight Prescription</h2>
          <p style={S.p}>Target weight is determined in priority order:</p>
          <ol style={S.list}>
            <li><strong>Progression data (3+ sessions)</strong> — uses your estimated 1RM with the inverse Epley formula:
              <em> target = e1RM ÷ (1 + (reps + RIR) ÷ 30)</em>, then rounds to the nearest plate increment</li>
            <li><strong>Recent session data (&lt;3 sessions)</strong> — uses your last working weight</li>
            <li><strong>No data</strong> — estimates from lift ratios (e.g., bench:squat:deadlift relationships) and body weight</li>
          </ol>
          <p style={S.p}>
            Plate rounding: barbells round to 5 lb, dumbbells to 5 lb, machines to 5 lb.
            During a cut, maintaining weight is treated as success (no forced progression).
          </p>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 6: Sets, Reps & Rest</h2>
          <ul style={S.list}>
            <li><strong>Sets</strong> — tiered by exercise role: primary (3-5), secondary (3-4), isolation (2-3), adjusted by goal and experience</li>
            <li><strong>Reps</strong> — goal-driven ranges: strength (3-6), hypertrophy (8-12), endurance (12-20)</li>
            <li><strong>RIR</strong> — Reps In Reserve target scales with goal: strength (2-3), hypertrophy (1-2), endurance (2-4)</li>
            <li><strong>Rest</strong> — computed from exercise demand score (muscle mass recruited, compound vs isolation, CNS load) × goal multiplier. Range: 30-300 seconds</li>
            <li><strong>Tempo</strong> — eccentric-pause-concentric prescription based on goal and exercise type</li>
          </ul>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 7: Time Constraints</h2>
          <p style={S.p}>
            The workout is fit to your time budget. If exercises exceed your session duration,
            lowest-priority exercises are removed. If time remains, additional exercises are added
            from the pool — targeting under-trained muscle groups first.
          </p>
          <p style={S.p}>
            Exercises are ordered: compounds first (sorted by CNS demand), then isolations.
            Historical exercise order is used as a minor tiebreaker, not a primary driver.
          </p>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Step 8: Scaling Factors</h2>
          <ul style={S.list}>
            <li><strong>Experience level</strong> — beginners get fewer sets (×0.75), advanced get more (×1.15)</li>
            <li><strong>Age</strong> — volume decreases ~0.5%/year past 30, progression rate ~0.8%/year past 30</li>
            <li><strong>Caloric phase</strong> — cutting reduces MRV 10%, bulking increases 8%</li>
            <li><strong>Sport focus</strong> — in-season reduces gym volume, adds sport-specific prehab exercises</li>
          </ul>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Goal Scoring</h2>
          <p style={S.p}>
            Your goal progress score (0-100) is computed from weighted signals specific to each goal.
            An <strong>outcome cap</strong> prevents inflated scores — if the primary metric isn't moving
            (e.g., weight not dropping for fat loss, strength index not rising), the score is hard-capped
            regardless of how good the supporting signals look.
          </p>
          <p style={S.sub}>Fat Loss</p>
          <p style={S.p}>Primary: weight trend (35%). Supporting: calories burned, active minutes, steps, workout calorie burn, strength retention, HR zones. Cap at 35 if no weight loss detected.</p>
          <p style={S.sub}>Strength</p>
          <p style={S.p}>Primary: strength index trend (30%). Supporting: lift progression, volume load trend. Cap at 55 if strength not rising.</p>
          <p style={S.sub}>Hypertrophy</p>
          <p style={S.p}>Primary: weekly volume trend (25%). Supporting: volume coverage across muscle groups, body weight trend, lift progression. Cap at 60 if volume declining.</p>
          <p style={S.sub}>Endurance</p>
          <p style={S.p}>Primary: cardio volume (25%). Supporting: RHR trend, active minutes, HRV, strength maintenance, sleep. Cap at 55 if cardio &lt;2x/week.</p>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>What the Model Does NOT Do</h2>
          <ul style={S.list}>
            <li>Does not use Fitbit body weight (only your manual entries)</li>
            <li>Does not use a black-box neural network — every decision is traceable</li>
            <li>Does not let the LLM modify workouts — it only analyzes and comments</li>
            <li>Does not guess when data is missing — it tells you what's missing</li>
            <li>Does not hardcode weight prescriptions — derives from your actual 1RM data</li>
          </ul>
        </div>

        <div style={S.section}>
          <h2 style={S.sectionTitle}>Research References</h2>
          <ul style={S.list}>
            <li>Schoenfeld et al. (2016) — Resistance training frequency and muscle growth</li>
            <li>Helms et al. (2014) — Evidence-based fat loss rates (0.5-1% BW/week)</li>
            <li>Willardson (2006) — Rest interval effects on strength and hypertrophy</li>
            <li>Levine (2004) — NEAT as primary TDEE component</li>
            <li>Longland et al. (2016) — Muscle preservation during caloric deficit</li>
            <li>Mujika & Padilla (2000) — Detraining onset and return-to-training protocols</li>
            <li>Häkkinen et al. (2001) — Age-related MRV changes</li>
            <li>Damas et al. (2019) — Myofibrillar protein synthesis and recovery</li>
            <li>Banister (1991) — Fitness-fatigue impulse-response model</li>
          </ul>
        </div>

      </div>
    </div>
  )
}
