/**
 * LLM Workout Refinement Endpoint
 *
 * Auth-protected Vercel serverless function that takes the rules engine output
 * and refines it using an LLM (OpenAI) with exercise science system prompt.
 *
 * The LLM acts as a reviewer/refiner — it does NOT generate workouts from scratch.
 * The rules engine (workoutEngine.ts) does the heavy lifting.
 *
 * POST /api/generate-workout
 * Body: { workout, profile, preferences }
 * Headers: Authorization: Bearer <supabase_access_token>
 */

import { extractUser } from './_shared/auth.js';

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

const SYSTEM_PROMPT = `You are an evidence-based exercise science expert acting as a workout reviewer.

You are given a workout that was generated by a deterministic rules engine. Your job is to REVIEW and REFINE it, not rebuild it.

Evidence base you operate from:
- Schoenfeld et al. (2017) dose-response meta-analysis for volume
- Helms, Morgan & Valdez training pyramid methodology
- Nuckols (Stronger By Science) practical programming guidelines
- Krieger (2010) single vs multiple sets meta-analysis
- Damas et al. (2019) on training-induced muscle damage and hypertrophy

The product uses an expanded muscle taxonomy (e.g. upper, mid, and lower chest; upper, mid, and lower traps; rotator cuff; hip flexors) rather than single buckets like "chest" or "traps"—use that framing when judging coverage and balance.

Your review should check:
1. Exercise ordering: compounds before isolations, no counterproductive pairings
2. Injury safety: ensure no exercise conflicts with reported injuries
3. Volume sanity: no single muscle group getting >10 direct sets in one session
4. Movement pattern coverage: if targeting chest, ensure upper, mid, and lower chest are adequately covered across the session
5. Exercise variety: suggest swaps if the same exercise appears too frequently
6. Rest time appropriateness for the rep range and exercise type
7. Tempo prescription matches the training goal
8. Mesocycle phase awareness: if a mesocycle phase is provided (accumulation/loading/overreach/deload), ensure the workout aligns with phase goals

Respond with ONLY valid JSON matching this schema:
{
  "approved": boolean,
  "exercises": [same format as input, with any modifications],
  "modifications": [{ "exercise": string, "change": string, "reason": string }],
  "sessionNotes": string
}

Do NOT add exercises. Only swap, reorder, or adjust existing ones.
Do NOT change the training goal or overall session structure.
Keep modifications minimal and well-justified.`;

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const user = await extractUser(req);
  if (!user) {
    return res.status(401).json({ error: 'Invalid or expired token' });
  }

  const { workout, profile, preferences } = req.body;

  if (!workout || !profile) {
    return res.status(400).json({ error: 'Missing workout or profile in request body' });
  }

  // If no OpenAI key, return the workout as-is (rules engine only mode)
  if (!OPENAI_API_KEY) {
    return res.status(200).json({
      workout,
      llmRefined: false,
      message: 'No OpenAI API key configured — returning rules engine output directly',
    });
  }

  try {
    const userMessage = JSON.stringify({
      workout: {
        exercises: workout.exercises,
        trainingGoal: workout.trainingGoal,
        deloadActive: workout.deloadActive,
        muscleGroupsFocused: workout.muscleGroupsFocused,
      },
      profile: {
        trainingFrequency: profile.trainingFrequency,
        bodyWeightTrend: profile.bodyWeightTrend,
        deloadRecommendation: profile.deloadRecommendation,
        plateauDetections: profile.plateauDetections?.filter(p => p.isPlateaued),
        imbalanceAlerts: profile.imbalanceAlerts,
        sleepCoefficients: profile.sleepCoefficients,
        mesocyclePhase: profile.mesocyclePhase,
        experienceLevel: profile.experienceLevel,
      },
      preferences: {
        injuries: preferences?.injuries ?? [],
        training_goal: preferences?.training_goal ?? workout.trainingGoal,
        equipment_access: preferences?.equipment_access ?? 'full_gym',
      },
    });

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userMessage },
        ],
        temperature: 0.3,
        max_tokens: 2000,
        response_format: { type: 'json_object' },
      }),
    });

    if (!response.ok) {
      const errBody = await response.text();
      console.error('OpenAI API error:', errBody);
      return res.status(200).json({
        workout,
        llmRefined: false,
        message: 'LLM refinement failed — returning rules engine output',
      });
    }

    const completion = await response.json();
    const content = completion.choices?.[0]?.message?.content;

    if (!content) {
      return res.status(200).json({ workout, llmRefined: false });
    }

    const refinement = JSON.parse(content);

    if (refinement.approved && (!refinement.modifications || refinement.modifications.length === 0)) {
      return res.status(200).json({
        workout,
        llmRefined: true,
        modifications: [],
        sessionNotes: refinement.sessionNotes || '',
      });
    }

    // Apply modifications to the workout
    const refinedWorkout = { ...workout };
    if (refinement.exercises) {
      refinedWorkout.exercises = refinement.exercises;
    }

    return res.status(200).json({
      workout: refinedWorkout,
      llmRefined: true,
      modifications: refinement.modifications || [],
      sessionNotes: refinement.sessionNotes || '',
    });
  } catch (err) {
    console.error('LLM refinement error:', err);
    return res.status(200).json({
      workout,
      llmRefined: false,
      message: 'LLM refinement failed — returning rules engine output',
    });
  }
}
